name: Publish Docker image
on:
  release:
    types: [created]
jobs:
  publish-image:
    name: Push Docker image to Docker Hub
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.7' # The Go version to download (if necessary) and use.

      - name: imports
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: imports
          token: ${{ secrets.GITHUB_TOKEN }}

        - name: Errcheck
          uses: grandcolline/golang-github-actions@v1.1.0
          with:
            run: errcheck
            token: ${{ secrets.GITHUB_TOKEN }}


        - name: lint
          uses: grandcolline/golang-github-actions@v1.1.0
          with:
            run: lint
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: shadow
          uses: grandcolline/golang-github-actions@v1.1.0
          with:
            run: shadow
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: check
          uses: grandcolline/golang-github-actions@v1.1.0
          with:
            run: staticcheck
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: sec
          uses: grandcolline/golang-github-actions@v1.1.0
          with:
            run: sec
            token: ${{ secrets.GITHUB_TOKEN }}
            flags: "-exclude=G104"
#
#      - name: Backup PVC - e2e
#        run: make -C backup/pvc/ docker-e2e UID=$(id -u) GID=$(id -g)

#      - name: Jenkins Operator - e2e
#        uses: sth

#      - name: Jenkins Operator Helm Chart - e2e
#        uses: sth

#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: my-docker-hub-namespace/my-docker-hub-repository
#          tag_with_ref: true