name: Publish Docker image
on:
  release:
    types: [created]
jobs:
  publish-image:
    name: Push Docker image to Docker Hub
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.7' # The Go version to download (if necessary) and use.

      - name: go-dep
        run: make go-dependencies

#      - name: imports
#        uses: grandcolline/golang-github-actions@v1.1.0
#        with:
#          run: imports

      - name: Backup PVC - e2e
        run: make -C backup/pvc/ docker-e2e UID=$(id -u) GID=$(id -g)

#      - name: Jenkins Operator - e2e
#        uses: sth

#      - name: Jenkins Operator Helm Chart - e2e
#        uses: sth

#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: my-docker-hub-namespace/my-docker-hub-repository
#          tag_with_ref: true